name: 🧪 Lint

on:
  push:
    branches:
      - master
      - feat/serde_yml
  pull_request:
    branches:
      - feat/serde_yml
  release:
    types: [created]

jobs:
  all:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install Rust
        run: |
          rustup update stable
          rustup component add clippy
      - name: Check lints
        run: cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings -A clippy::print_stdout -A clippy::print_stderr
